import { generate } from "@ecchi-js/language";
import webpack from 'webpack';

export interface LoaderOptions {}

function ecchiLoader(
  this: webpack.LoaderContext<LoaderOptions>,
  _contents: string,
  _inputSourceMap?: Record<string, any>
) {
  const { version, webpack, resourcePath, callback } = this;
  generate(resourcePath).then((output) => {
    const outputString = `/***********************************************
 * This file was generated by @ecchi-ts/webpack-loader v${version}
 * Is this in "webpack mode": ${webpack}
 ***********************************************/
${output}
`;
    callback(null, outputString);
  });
}

export default ecchiLoader;
