import { spawnSync } from 'node:child_process';
import webpack from 'webpack';

export interface LoaderOptions {}

function ecchiLoader(
  this: webpack.LoaderContext<LoaderOptions>,
  _contents: string,
  _inputSourceMap?: Record<string, any>
): string {
  const { version, webpack, resourcePath } = this;
  const mainFile = require.resolve("@ecchi-js/cli");
  const args = [mainFile, resourcePath].map(s => s.replace(/\\/g, '/'));
  const output = spawnSync(process.execPath, args, { encoding : 'utf8' });
  return `/***********************************************
 * This file was generated by @ecchi-ts/webpack-loader v${version}
 * Is this in "webpack mode": ${webpack}
 ***********************************************/
${output.stdout}
`;
}

export default ecchiLoader;
